#!/usr/bin/python
"""
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org/>
"""
import evdev
import qcontrol
import select
import glob
import logging

from time import sleep

# setup my logger
logger = logging.getLogger("qnappy")
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)
formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
ch.setFormatter(formatter)

logger.addHandler(ch)

def main():
  """
  this monitors the NAS's vitals, and also
  watches for button events.
  """
  nas = qcontrol.Ts219()
  
  # grab existing devices.  It won't react to devices that are
  # inserted after starting.

  EVDEV_DEVICES=glob.glob("/dev/input/event*")
  ev  = evdev.DeviceGroup(EVDEV_DEVICES)
    
  try:
    while 1:
      # watch for incoming event device nodes...
      readers = [nas.fd] + ev.fds
      writers = [nas.fd]
      writers = []
      exceptions = []

      r, w, x = select.select(readers, writers, exceptions)
      
      for reader in r:
        if reader==nas.fd:
          # logger.info "OMG NASFD"
          nas.process_data(reader.read(1))
      
        elif reader in ev.fds:
          # logger.info "OMG EV!"
          e = ev.next_event()
          logger.info( dir(e))

        else:
          pass 
  except KeyboardInterrupt, e:
    logger.warn("Outta here!")
    nas.send_command("status_greenon")
    nas.send_command("usb_off")
    nas.send_command("fan_silence")
    nas.send_command("powerled_on")
  except:
    import traceback
    exc_type, exc_value, exc_traceback = sys.exc_info()
    print sys.exc_info()  

if __name__=='__main__':
  main()  
  